// src/app/components/planning-lab-view/planning-lab-view.component.ts
import { Component } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import { localStorageSignal } from '../../../core/local-storage-signal';
import { DailyBacklogViewComponent } from '../daily-backlog-view/daily-backlog-view.component';
import { GeneralBacklogViewComponent } from '../general-backlog-view/general-backlog-view.component';

type PlanningLabTab = 'daily' | 'general';

@Component({
  selector: 'app-planning-lab-view',
  standalone: true,
  imports: [TranslatePipe, DailyBacklogViewComponent, GeneralBacklogViewComponent],
  templateUrl: './planning-lab-view.component.html',
  styleUrl: './planning-lab-view.component.css',
})
export class PlanningLabViewComponent {
  readonly tab = localStorageSignal<PlanningLabTab>('productivist.planningLabTab', 'daily');
}

<main class="planning-lab">
  <div class="planning-lab__header">
    <h2>{{ 'planningLab.title' | translate }}</h2>
    <div class="planning-lab__tabs" role="tablist">
      <button
        type="button"
        role="tab"
        [attr.aria-selected]="tab() === 'daily'"
        [class.active]="tab() === 'daily'"
        (click)="tab.set('daily')"
      >
        {{ 'planningLab.dailyBacklog' | translate }}
      </button>
      <button
        type="button"
        role="tab"
        [attr.aria-selected]="tab() === 'general'"
        [class.active]="tab() === 'general'"
        (click)="tab.set('general')"
      >
        {{ 'planningLab.generalBacklog' | translate }}
      </button>
    </div>
  </div>

  @if (tab() === 'daily') {
    <app-daily-backlog-view />
  } @else {
    <app-general-backlog-view />
  }
</main>

// src/components/PlanningLabView.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { useLocalStorage } from '../composables/useLocalStorage'
import DailyBacklogView from './DailyBacklogView.vue'
import GeneralBacklogView from './GeneralBacklogView.vue'

type PlanningLabTab = 'daily' | 'general'

const { t } = useI18n()
const tab = useLocalStorage<PlanningLabTab>('productivist.planningLabTab', 'daily')
</script>

<template>
  <main class="planning-lab">
    <div class="planning-lab__header">
      <h2>{{ t('planningLab.title') }}</h2>
      <div class="planning-lab__tabs" role="tablist">
        <button
          type="button"
          role="tab"
          :aria-selected="tab === 'daily'"
          :class="{ active: tab === 'daily' }"
          @click="tab = 'daily'"
        >
          {{ t('planningLab.dailyBacklog') }}
        </button>
        <button
          type="button"
          role="tab"
          :aria-selected="tab === 'general'"
          :class="{ active: tab === 'general' }"
          @click="tab = 'general'"
        >
          {{ t('planningLab.generalBacklog') }}
        </button>
      </div>
    </div>

    <DailyBacklogView v-if="tab === 'daily'" />
    <GeneralBacklogView v-else />
  </main>
</template>

<style scoped>
.planning-lab {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 1rem;
  padding: 1rem;
  max-width: 1100px;
  width: 100%;
  margin: 0 auto;
}

.planning-lab__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 1rem;
  flex-wrap: wrap;
}

.planning-lab__header h2 {
  margin: 0;
}

.planning-lab__tabs {
  display: flex;
  gap: 0.5rem;
}

.planning-lab__tabs button {
  background: none;
  border: 1px solid var(--color-border);
  border-radius: 999px;
  color: var(--color-text-muted);
  padding: 0.35rem 1rem;
}

.planning-lab__tabs button.active {
  background-color: var(--color-primary);
  color: var(--color-primary-contrast);
  border-color: var(--color-primary);
}
</style>
