// src/components/TodoForm.vue
<script setup lang="ts">
import { nextTick, ref, useId } from 'vue'
import { useI18n } from 'vue-i18n'
import { useTodosStore } from '../stores/todos'
import type { Priority } from '../types/todo'

const props = defineProps<{ projectId?: string; milestoneId?: string }>()
const { t } = useI18n()
const todos = useTodosStore()

const title = ref('')
const description = ref('')
const importance = ref<Priority>('medium')
const urgency = ref<Priority>('medium')
const tagsInput = ref('')
const pomodorosForTermination = ref('')
const expanded = ref(false)
const formEl = ref<HTMLFormElement | null>(null)
const titleInputEl = ref<HTMLInputElement | null>(null)
const tagSuggestionsId = useId()

async function submit() {
  const trimmed = title.value.trim()
  if (!trimmed) return
  const tags = tagsInput.value
    .split(',')
    .map((tag) => tag.trim())
    .filter(Boolean)
  const pomodoros = parseInt(pomodorosForTermination.value, 10)
  todos.addTodo({
    title: trimmed,
    description: description.value.trim() || undefined,
    importance: importance.value,
    urgency: urgency.value,
    tags,
    projectId: props.projectId,
    milestoneId: props.milestoneId,
    pomodorosForTermination: Number.isFinite(pomodoros) && pomodoros > 0 ? pomodoros : undefined,
  })
  title.value = ''
  description.value = ''
  tagsInput.value = ''
  pomodorosForTermination.value = ''
  expanded.value = false
  await nextTick()
  titleInputEl.value?.focus()
}

function onFocusOut(event: FocusEvent) {
  const next = event.relatedTarget as Node | null
  if (formEl.value && next && formEl.value.contains(next)) return
  expanded.value = false
}
</script>

<template>
  <form
    ref="formEl"
    class="todo-form"
    :class="{ 'todo-form--expanded': expanded }"
    @submit.prevent="submit"
    @focusin="expanded = true"
    @focusout="onFocusOut"
  >
    <input
      ref="titleInputEl"
      v-model="title"
      type="text"
      class="todo-form__title"
      :placeholder="t('todo.addPlaceholder')"
    />
    <div v-if="expanded" class="todo-form__details">
      <div class="todo-form__row">
        <label>
          {{ t('todo.importance') }}
          <select v-model="importance">
            <option value="low">{{ t('todo.low') }}</option>
            <option value="medium">{{ t('todo.medium') }}</option>
            <option value="high">{{ t('todo.high') }}</option>
          </select>
        </label>
        <label>
          {{ t('todo.urgency') }}
          <select v-model="urgency">
            <option value="low">{{ t('todo.low') }}</option>
            <option value="medium">{{ t('todo.medium') }}</option>
            <option value="high">{{ t('todo.high') }}</option>
          </select>
        </label>
      </div>
      <input v-model="tagsInput" type="text" :list="tagSuggestionsId" :placeholder="t('todo.tagsPlaceholder')" />
      <datalist :id="tagSuggestionsId">
        <option v-for="tag in todos.allTags" :key="tag" :value="tag" />
      </datalist>
      <textarea v-model="description" rows="2" :placeholder="t('todo.descriptionPlaceholder')" />
      <label class="todo-form__pomodoros">
        {{ t('todo.pomodorosForTermination') }}
        <input
          v-model="pomodorosForTermination"
          type="number"
          min="1"
          :placeholder="t('todo.pomodorosForTerminationPlaceholder')"
        />
      </label>
      <button type="submit">{{ t('todo.add') }}</button>
    </div>
  </form>
</template>

<style scoped>
.todo-form {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  background-color: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: 8px;
  padding: 1rem;
}

.todo-form input,
.todo-form select,
.todo-form textarea {
  background-color: var(--color-surface);
  color: var(--color-text);
  border: 1px solid var(--color-border);
  border-radius: 4px;
  padding: 0.4rem 0.6rem;
  font-family: inherit;
}

.todo-form textarea {
  width: 100%;
  resize: vertical;
}

.todo-form__pomodoros {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
  font-size: 0.8rem;
  color: var(--color-text-muted);
}

.todo-form__title {
  width: 100%;
}

.todo-form__details {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.todo-form__row {
  display: flex;
  gap: 1rem;
  flex-wrap: wrap;
}

.todo-form__row label {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
  font-size: 0.8rem;
  color: var(--color-text-muted);
  flex: 1 1 120px;
}

.todo-form button {
  align-self: flex-start;
  background-color: var(--color-primary);
  color: var(--color-primary-contrast);
  border: none;
  border-radius: 6px;
  padding: 0.5rem 1.25rem;
}
</style>

// src/app/components/todo-form/todo-form.component.ts
import { Component, ElementRef, inject, input, signal, viewChild } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { TranslatePipe } from '@ngx-translate/core';
import { TodosService } from '../../../services/todos.service';
import type { Priority } from '../../../types/todo';

let nextId = 0;

@Component({
  selector: 'app-todo-form',
  standalone: true,
  imports: [FormsModule, TranslatePipe],
  templateUrl: './todo-form.component.html',
  styleUrl: './todo-form.component.css',
})
export class TodoFormComponent {
  readonly todos = inject(TodosService);

  readonly projectId = input<string | undefined>();
  readonly milestoneId = input<string | undefined>();

  readonly tagSuggestionsId = `todo-form-tags-${nextId++}`;

  readonly title = signal('');
  readonly description = signal('');
  readonly importance = signal<Priority>('medium');
  readonly urgency = signal<Priority>('medium');
  readonly tagsInput = signal('');
  readonly pomodorosForTermination = signal('');
  readonly expanded = signal(false);

  private readonly formEl = viewChild<ElementRef<HTMLFormElement>>('formEl');
  private readonly titleInputEl = viewChild<ElementRef<HTMLInputElement>>('titleInputEl');

  submit(): void {
    const trimmed = this.title().trim();
    if (!trimmed) return;
    const tags = this.tagsInput()
      .split(',')
      .map((tag) => tag.trim())
      .filter(Boolean);
    const pomodoros = parseInt(this.pomodorosForTermination(), 10);
    this.todos.addTodo({
      title: trimmed,
      description: this.description().trim() || undefined,
      importance: this.importance(),
      urgency: this.urgency(),
      tags,
      projectId: this.projectId(),
      milestoneId: this.milestoneId(),
      pomodorosForTermination: Number.isFinite(pomodoros) && pomodoros > 0 ? pomodoros : undefined,
    });
    this.title.set('');
    this.description.set('');
    this.tagsInput.set('');
    this.pomodorosForTermination.set('');
    this.expanded.set(false);
    queueMicrotask(() => this.titleInputEl()?.nativeElement.focus());
  }

  onFocusOut(event: FocusEvent): void {
    const next = event.relatedTarget as Node | null;
    const form = this.formEl()?.nativeElement;
    if (form && next && form.contains(next)) return;
    this.expanded.set(false);
  }
}

<form
  #formEl
  class="todo-form"
  [class.todo-form--expanded]="expanded()"
  (submit)="$event.preventDefault(); submit()"
  (focusin)="expanded.set(true)"
  (focusout)="onFocusOut($event)"
>
  <input
    #titleInputEl
    [ngModel]="title()"
    (ngModelChange)="title.set($event)"
    name="title"
    type="text"
    class="todo-form__title"
    [placeholder]="'todo.addPlaceholder' | translate"
  />
  @if (expanded()) {
    <div class="todo-form__details">
      <div class="todo-form__row">
        <label>
          {{ 'todo.importance' | translate }}
          <select [ngModel]="importance()" (ngModelChange)="importance.set($event)" name="importance">
            <option value="low">{{ 'todo.low' | translate }}</option>
            <option value="medium">{{ 'todo.medium' | translate }}</option>
            <option value="high">{{ 'todo.high' | translate }}</option>
          </select>
        </label>
        <label>
          {{ 'todo.urgency' | translate }}
          <select [ngModel]="urgency()" (ngModelChange)="urgency.set($event)" name="urgency">
            <option value="low">{{ 'todo.low' | translate }}</option>
            <option value="medium">{{ 'todo.medium' | translate }}</option>
            <option value="high">{{ 'todo.high' | translate }}</option>
          </select>
        </label>
      </div>
      <input
        [ngModel]="tagsInput()"
        (ngModelChange)="tagsInput.set($event)"
        name="tags"
        type="text"
        [attr.list]="tagSuggestionsId"
        [placeholder]="'todo.tagsPlaceholder' | translate"
      />
      <datalist [id]="tagSuggestionsId">
        @for (tag of todos.allTags(); track tag) {
          <option [value]="tag"></option>
        }
      </datalist>
      <textarea
        [ngModel]="description()"
        (ngModelChange)="description.set($event)"
        name="description"
        rows="2"
        [placeholder]="'todo.descriptionPlaceholder' | translate"
      ></textarea>
      <label class="todo-form__pomodoros">
        {{ 'todo.pomodorosForTermination' | translate }}
        <input
          [ngModel]="pomodorosForTermination()"
          (ngModelChange)="pomodorosForTermination.set($event)"
          name="pomodorosForTermination"
          type="number"
          min="1"
          [placeholder]="'todo.pomodorosForTerminationPlaceholder' | translate"
        />
      </label>
      <button type="submit">{{ 'todo.add' | translate }}</button>
    </div>
  }
</form>
